Initial QVTo Transformations for SPD Semantic
PalladioSimulator/Palladio-Addons-SPD-Metamodel pull request #5
Opened 2023-06-07 07:47 UTC by klinakuf

Through this PR, I intend to have QVTo transformations---that define the execution semantic behind SPD models---located together with the rest of SPD related code. 

**The intended use of the transformations script is threefold:** 

- First, one can execute a certain scaling policy on a Palladio model, to obtain a new Palladio model (scaled version) which then can be simulated. It can also be used to observe/debug quickly the effect of executing a scaling policy.  
-  Second, one can build a program that constructs a labelled transition system that explores all the possible states of the Palladio models under a set of active scaling policies where each transition represents one enacted scaling policy and verify certain properties/constraints. 
- Third, last but the most important one, we can use these scripts to transform the model during simulation in Slingshot. 

**Considerations:** 
- Right now the semantic is specified under the assumption that a policy has been already enacted.  The semantic does not specify how that enactment happen i.e., it does not define the semantic of the triggering. A possible extension would be to include the interpretation of RuntimeMeasurement models and to define also triggering. However, we would make the use cases one and two more difficult. 

**Structure of the code:** 
* archive [no need to look at], archive that eventually should be deleted
* pcm.helpers - here I reuse scripts that were written in the context of ATs and by other contributors in the Palladio context. Not all are relevant, I tread the scripts as a library to manipulate/construct Palladio models. 
* spd.common - here I define common aspects of the SPD interpretation. For example, you can look at the AdjustmentCalculator that defines the calculation based on an AdjustmentType given the currentSize of a targetGroup. 
* spd.bottomup - here I define (currently), the bottomup transformation of a Palladio model given policies that target an ElasticInfrastructure (which points to a ResourceEnvironment). It is named bottomup to reflect the semantic behind, that first the ResourceEnvironment is adjusted based on the AdjustmentType and then the services are replicated accordingly. 

**Future development and why to merge this partial semantic:**
The semantic is not fully complete, while it does not yet define the case in which policies target services and not infrastructure. However, I would argue that since it defines the semantic for the ElasticInfrastructure, we could use this code for testing and integration purposes with the simulator to have the initial use cases demonstratable.  

In the future then, an spd.topdown package would be added which would contain transformation scripts that first scale the services to the desired state and then adjust the infrastructure accordingly.

2023-06-19 06:31 UTC, stiesssh requested changes
please add the `.project`and `.settings`. It makes it a hella lot easier to import projects into eclipse and also we have them there for all (?) other bundles. at least all i just checked.

2023-06-19 06:39 UTC, stiesssh commented on bundles/org.palladiosimulator.spd.semantic.transformations/README.md
> +An example model is provided as part of this repository named `test-spd`.
there is noch such thing as a `test-spd`. 
i remember it from the gitlab repo though. did you rename it, oder forgot to copy it?

2023-06-20 15:12 UTC, stiesssh reviewed
- regarding the helpers it's a bit unclear to me, whether you wrote them, or whether someone else wrote them. except for the one where it tags that benjamin as author. and in case of copies, where do they come from? 
- all constructors in `Loadbalancing.qvto` are also present in the `Constructors.qvto`, except that `Loadbalancing.qvto` kindly provides some documentation, while `Constructors.qvto` does not.   -- why do we have/need this code duplicate? 
- there are even more duplicate helpers that are in both `Wiring.qvto` and `Loadbalancing.qvto`.

note : i did not yet look into the LoadBalancerCreation, but i want to submit this already anyway.

2023-06-21 06:17 UTC, stiesssh reviewed
i'm sorry to only notice this now, but for me the transformations change the resource environment only, but the allocation and assembly remain unchanged. at least after the transformation. i'd assume that this is a propagation problem? i.e. changes happen during transformation, but are not propagated to after the transformation?

2023-06-21 06:28 UTC, stiesssh commented on bundles/org.palladiosimulator.spd.semantic.transformations/transformations/spd/bottomup/BottomUpTransformation.qvto
> +		cfg.targetCfgs[ServiceGroupCfg]->map transformServiceGroup(cfg.enactedPolicy, elasticInfrastructureCfg, system, allocation);
for my example, `cfg.targetCfgs[ServiceGroupCfg]` is empty. and the no allocation / assemblies are create.

2023-06-22 16:13 UTC, klinakuf commented on bundles/org.palladiosimulator.spd.semantic.transformations/transformations/spd/bottomup/BottomUpTransformationServices.qvto
> +	if(newAssemblies->size()=0 and elasticInfraCfg.elements->size()<>self.elements->size()){
it is about scaling in, but there was a bug in the condition and in the selection of assemblies which should continoue to exist

2023-06-22 16:20 UTC, klinakuf commented
I tackled some of the concerns raised in this review. @stiesssh you can look over the provided changes, unless you see something critical, I would merge this in order to proceed and build upon, by keeping in mind that eventually the code that has been created by others for transforming pcm-related models has to be revised and cleaned up.

2023-06-23 08:03 UTC, stiesssh approved these changes
lgtm :D 

also: i changed the classpath entry, because it threw and error on my machine D: hopefully it still work on yours now D:

2023-06-23 10:11 UTC, merged